### ISSUE TITLE
Crash with Enchiridion book

### ISSUE THREAD

**Issue by rigerc** [Vazkii/AkashicTome#1]
Using my self-made Enchiridion book I get a crash when I click on the book in the GUI.

Crash log: http://pastebin.com/zpcL4Fk5
Using Forge 2075, MC 1.10

**Comment by univrsal** [comment]
Happened to me aswell, I'll take a guess and say it's because someone accidentally imported scala stuff :P

**Comment by Vazkii** [comment]
Fixed with https://github.com/Vazkii/AkashicTome/commit/6c2f9da635d1f5dcafc66f171f05fec3b6ec2d6d
