### ISSUE TITLE
[Bug]?? too many books???

### ISSUE THREAD

**Issue by phorced** [Vazkii/AkashicTome#101]
Book does not look right
![2022-08-31_17 24 43](https://user-images.githubusercontent.com/110329471/187718540-7d24b244-5b57-4edb-aad1-f824536e87af.png)

**Comment by Raidobw2** [comment]
Having the same issue in the 1.18.2 version of Akashic Tome for Forge
![image](https://user-images.githubusercontent.com/17010632/188418963-e3be0fdc-cbb4-4476-ac2e-d79a82894be7.png)

**Comment by draymone** [comment]
Same problem, in 1.18.2 with the 1.5-20 version of the mod.
![image](https://user-images.githubusercontent.com/64921768/189336011-e83fc2da-8f93-4368-aa1d-c469cd9c0a6f.png)

**Comment by SamuelRUM** [comment]
Same thing here, it's really annoying.
![image](https://user-images.githubusercontent.com/112104519/189487711-d79f6be4-5bdd-4205-92da-d16436770db2.png)

**Comment by Kanzaji** [comment]
This is known bug, already reported (#92), but they seems to not fix this, even tho it affects most of bigger modpacks that use Akashic Tome.

**Comment by Cerbrus** [comment]
A fix was implemented in this commit: https://github.com/VazkiiMods/AkashicTome/commit/d5d14626a60e5220b6c78eaf18de5a892000a0cf

Disable the book render in your options, and it'll be fine again:

![image](https://github.com/VazkiiMods/AkashicTome/assets/2911988/796ec0ce-7850-4b7b-a22c-cd126b007a96)
