### ISSUE TITLE
[1.19.2] failed to load correctly

### ISSUE THREAD

**Issue by CubeTwo** [Vazkii/AkashicTome#105]
game version: 1.19.2
forge: 43.1.52
mod version: 1.6-21
AutoRegLib-1.8-54

cannot load gave with mod, says : Failure message: Akashic Tome (akashictome) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null

crash log : https://paste.ee/p/hQyOc

**Comment by ArcusMG** [comment]
Also get this error, when only loading AkashicTome and Morph Tools. 

Forge version 43.1.52
AkashicTome 1.6-21
Morph-oTool 1.6-33
AutoRegLib-1.8-54

[latest.log](https://github.com/VazkiiMods/AkashicTome/files/10047831/latest.log)

**Comment by UrBoiTom** [comment]
I'm having the same issue

**Comment by Vazkii** [comment]
Note to self: stop trusting alwinfy to do ports
