### ISSUE TITLE
(1.19.2) Disconnect when opening certain books (Integrated Dynamics, Force Craft, Apotheosis)

### ISSUE THREAD

**Issue by robertmaxton42** [Vazkii/AkashicTome#109]
Opening certain books -- for example, _On the Dynamics of Integration_ from Integrate Dynamics, _Force and You_ from ForceCraft, chronicle of Shadows_ from Apotheosis, but also many others -- causes the game to disconnect with the message 

```
Internal Exception: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
```

Possibly useful data point: If armor with Block Reach is equipped, then the disconnect occurs whenever one attempts to switch books, including back to the base Tome.

I'm currently on the Direwolf20 1.19 modpack, but I can reproduce this bug with only AkashicTome and one of the listed mods.

**Comment by Uraneptus** [comment]
I could not reproduce this bug. If this is still relevant, please open a new issue and please attach a full log then
