### ISSUE TITLE
Some books in the upper row of the tome are not visible

### ISSUE THREAD

**Issue by Zulussuu** [Vazkii/AkashicTome#113]
The books in the top row are not visible due to the shifting interface.
![image](https://github.com/VazkiiMods/AkashicTome/assets/160519073/f6934937-b5f4-4a78-b674-878a673ab5a5)

**Comment by Uraneptus** [comment]
Oh wait, a fix was already added in version 1.6-23: https://github.com/VazkiiMods/AkashicTome/commit/d5d14626a60e5220b6c78eaf18de5a892000a0cf
