### ISSUE TITLE
profile disconnecting from world when making new world

### ISSUE THREAD

**Issue by BluePhoenix0120** [Vazkii/AkashicTome#114]
I am trying to make a fantasy pack for me and some friends and its pretty random at this point what mods will and wont cause this error to appear when making a world. here is my logs. 
[latest.log](https://github.com/user-attachments/files/15930451/latest.log)

**Comment by Uraneptus** [comment]
Nothing in this log suggests that AkashicTome is the issue. The end of the log says something about llibrary, so you may wanna check if that mod is causing problems
