### ISSUE TITLE
Akashic Tome duping several books

### ISSUE THREAD

**Issue by xenxero1** [Vazkii/AkashicTome#12]
https://github.com/Vazkii/AkashicTome/issues/5

I've experienced this glitch where an Ars Magica 2 dyed spell book, and certain blood-magic documentaion using Guide-API are unable to be removed from the akashic tome. Removal from the tome only results in a copy of these items being dropped on the ground, without them actually having the item removed from the book. 

Temporary fix: Find all items that do this and simply blacklist them by default in the config file.

**Comment by starg09** [comment]
Can confirm this still happening on 1.11.2, with Blood Magic's Sanguine Scientiem.

As a note, if you have, let's say, the manual from Modular Routers and the BM one, and drop the BM one first, it dupes and deletes the book from MR.

**Comment by Uraneptus** [comment]
I need to check if this is still happening on 1.20

**Comment by Uraneptus** [comment]
Irrelevant for 1.20.1
