### ISSUE TITLE
Add "Codex" to the list of whitelisted names

### ISSUE THREAD

**Issue by The-Fireplace** [Vazkii/AkashicTome#17]
This would allow the book from Embers, "Ancient Codex", to be added to the Akashic Tome by default.

**Comment by Sunconure11** [comment]
Just curious, but what's wrong with using the config for this mod? It would allow you to do this.

**Comment by The-Fireplace** [comment]
@Sunconure11
Nothing is wrong with using the config, I was just making a suggestion to include it by default.

**Comment by xenxero1** [comment]
I'm a fan of using more whitelisted names by default rather than manually adding in items. It's easier on modpack builders and greatly decreases the chance of missing a book.
