### ISSUE TITLE
Akashic Tome is lost when using Runic Tablet from Roots

### ISSUE THREAD

**Issue by RJS1997** [Vazkii/AkashicTome#2]
Using latest versions of Forge, Roots, Akashic Tome and AutoRegLib.

When selecting the Runic Tablet from the Akashic Tome it changes to the tablet as it should, but when you open the tablet it then changes to a normal tablet and the Akashic Tome is lost.

**Comment by Vazkii** [comment]
I'd report this to Roots. The item shouldn't be wiped of NBT like that in any case.
