### ISSUE TITLE
[1.12.2] Crash with Akashic Tome

### ISSUE THREAD

**Issue by NielsPilgaard** [Vazkii/AkashicTome#28]
Hey!

This appears to be the same issue as #19 
I guess it re-emerged somehow?
Crashlog: https://gist.github.com/NillerMedDild/5214acd32e953338b918921ce8fd96b7

Minecraft 1.12.2
Forge 1.12.2-14.23.1.2583
AkashicTome-1.2-10
AutoRegLib-1.3-15

**Comment by Uraneptus** [comment]
If this is still relevant in 1.20, please open a new issue
