### ISSUE TITLE
[Minor] Books from "GuideAPI" mod don't have proper mod in data tag

### ISSUE THREAD

**Issue by OrdinatorStouff** [Vazkii/AkashicTome#31]
Books from "GuideAPI" mod are registered by the GuideAPI mod but are responsible for other mods (i.e. Blood Magic, Cyclic, etc). This means the Tome's data tag refers to any such books as having the source mod be "guideapi"

I'm pretty sure the "akashictome:definedMod" tag is just for internal use anyway as far as I can tell but for consistency I'm not sure if this is something worth looking into.

```json
"akashictome:data": {
	guideapi: {
		id: "guideapi:mobtotems-mobtotems_guide",
		Count: 1 as byte,
		tag: {
			"akashictome:definedMod": "guideapi"
		},
		Damage: 0 as short
	},
	guideapi1: {
		id: "guideapi:cyclicmagic-guide",
		Count: 1 as byte,
		tag: {
			"akashictome:definedMod": "guideapi1"
		},
		Damage: 0 as short
	},
	guideapi2: {
		id: "guideapi:bloodmagic-guide",
		Count: 1 as byte,
		tag: {
			"akashictome:definedMod": "guideapi2"
		},
		Damage: 0 as short
	}
}
```

It's not a big deal to me I just noticed it and though it was worth pointing it out.

**Comment by Uraneptus** [comment]
Ah I see the problem yes. But since guideAPI is not supporting modern versions from what I can tell I will close this.
