### ISSUE TITLE
Suggestion: Allow pack makers to create unique tomes with a different texture

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Vazkii/AkashicTome#33]
In the modpack I'm working on, I want to give the player an Akashic Tome on world creation that contains every guide book. This cleans up the starting inventory and will hopefully drive players to actually read the manual.

I've added a recipe to this book and forced it to appear in JEI, but I'd also like to give the book a unique texture. This is where I hit a bit of a brick wall. To my knowledge, there's no way to change a texture based on NBT data.

I'd like the book to appear as a second item to the player, not as a slight variant of a normal tome. The implementation I'm using currently might be a bit confusing.

To make this accessible to pack makers, the best way to implement this would be as follows:

1. The player creates a tome with the desires books

2. The player runs a command such as `/akastictome create [name]`

3. Upon restarting the pack, a tome of a different color would exist as a new item containing the same books as were present in step 1.

There should be a way to change the textures, either using a file in the config folder or with a resource loader. Recipes can easily be changed with CraftTweaker, which is something all pack makers should have some experience with, so I don't think the mod needs to handle that.

**Comment by Uraneptus** [comment]
I'm pretty sure there are better ways to do this in modern versions.
