### ISSUE TITLE
1.12.2-1.2.10 Tome Not Accepting Any Books Regardless Of Config

### ISSUE THREAD

**Issue by TwitchtvCarbs** [Vazkii/AkashicTome#36]
No matter the config options it seems like the crafting recipe where it returns the tome with the book inside doesn't work. Basically what I mean is that when you go to put a book inside no matter the book or config it seems to not have an output for the recipe anymore. Not sure if anyone else has come across this yet?

**Comment by Uraneptus** [comment]
I can't confirm this in 1.20. if it's still happening for you in that version, pls open a new issue
