### ISSUE TITLE
Crash When Left + rRight Clicking

### ISSUE THREAD

**Issue by myrriad** [Vazkii/AkashicTome#39]
I had the Akashic Tome set to have the Botania book open (lol)
I left clicked, then right clicked the Akashic Tome pretty fast
I got a crash
https://pastebin.com/wmp67ryN
Akashic:1.2-10   
Forge:forge-14.23.4.2751 probably

**Comment by Uraneptus** [comment]
I need to have this confirmed for a newer version

**Comment by Uraneptus** [comment]
Not confirmed for 1.20.1
