### ISSUE TITLE
Texture issues with optifine

### ISSUE THREAD

**Issue by BigNasty1028** [Vazkii/AkashicTome#41]
I'm not 100% sure its an optifine issue, just when i ask in discord others that have the problem also have optifine enabled (i cant test without optifine because my pc is a toaster)
https://gyazo.com/3c30b2c0c34960f1949c1a7821a9e4f4
https://gyazo.com/d10407c8e41701be98891328c18e99bd
Modpack I'm using is All The Mods 3 remix v0.1.2
Most of the books you can get an idea of what it says, but for books like the Wizardry one its somewhat impossible to understand as the first line is covered

**Comment by Vazkii** [comment]
You're reporting this to the wrong mod. And yes, it's an optifine issue.
