### ISSUE TITLE
Tome breaking Thaumcraft when used in Thaumcraft table

### ISSUE THREAD

**Issue by DreamThorn** [Vazkii/AkashicTome#46]
This is related to issue #34, but that issue was closed despite not being fixed.

Both the Tome and the Thaumcraft crafting table was working fine, until I tried adding the Immersive Engineering manual to the tome, using thaumcraft's crafting table's grid.

Instead of adding the manual, it added a Perditio Vis Crystal, and then Thaumcraft's crafting stopped working; specifically, I could no longer create thaumometers.

The table was loaded with all 6 kinds of primal vis crystals.  I suspect it would have worked correctly if there weren't any vis crystals loaded in.

**Comment by DoomRater** [comment]
Can confirm, but I'm almost certain this is on Thaumcraft's end.  I'm going to refer to this over at DupeFix Project as Thaumcraft is dead in the water.  If there is a crystal in the arcane workbench, the tome will add the last crystal in the table instead of the manual.
