### ISSUE TITLE
Config resets on game load

### ISSUE THREAD

**Issue by WenXin20** [Vazkii/AkashicTome#52]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Akashic Tome v1.3.13`

I tried to add "document" to the accepted names in the config, but the config resets and erases any changes made to it when the game loads

**Comment by Shados** [comment]
I'm having the same problem. Amusingly, it appears to be doing this *even with the default config*, as the log file still has a `Configuration file ...\config\akashictome-common.toml is not correct. Correcting` line.

**Comment by Shados** [comment]
@WenXin20 I've submitted a PR to fix the issue, and if you want, I've uploaded a version built with the fix [here](https://shados.net/files/AkashicTome-1.3-13-config-load-fix.jar).

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please open a new issue
