### ISSUE TITLE
Cannot add multiple books from the same mod

### ISSUE THREAD

**Issue by WenXin20** [Vazkii/AkashicTome#53]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Akashic Tome v1.3.13`

I tried to add multiple books from the same mod to the tome, but it does not seem to work.

**Comment by DoomRater** [comment]
This worked in 1.12.2, or at least I was able to add multiple blueprints to the Akashic Tome when I configured it to do so.  Has something changed since then?

**Comment by DoomRater** [comment]
Yes indeed.  There was special handling in the 1.12.2 version of the code that is not present in the 1.15.2 update.  Looks like a copy and paste oversight from the Morph-o-Tool.
https://github.com/Vazkii/AkashicTome/blob/647da9c9033600a89f09bb726b7a0791e8950784/src/main/java/vazkii/akashictome/AttachementRecipe.java#L68-L75

**Comment by nanonestor** [comment]
Possible this could be remedied?  In 1.16.5 this issue is still present - can only add one book for each mod.  Several popular mods these days have multiple books (Tinker's Construct and Cooking For Blockheads for example.)

**Comment by benbenlaw** [comment]
please we need this fix, also same issues with morphing tool

**Comment by DoomRater** [comment]
The Morph-o-tool never had support for more than one tool at a time, and the way it functions would make that functionality problematic.  Suppose you look at a block- which of the two tools should a Morph-o-tool become, if multiple tools are allowed?

**Comment by benbenlaw** [comment]
i mean you cant put in 2 things from the same mod into the morphing tool

**Comment by DoomRater** [comment]
1. This is not the issues page for Morph-o-tool.
2. I just got through explaining why that behavior would be a probolem.

**Comment by benbenlaw** [comment]
i know just saying, so is this the same will akashic tome never be able to support 2 different books from one mod?

**Comment by ffuentesm** [comment]
This is a pity. I mainly got Akeshick Tome to store my Tinker's Manuals (5 books in total)

**Comment by DoomRater** [comment]
As much as I want to say more people commenting on the state of things will make things move faster, no one has even commented on the code difference I pointed out.  I have been unable to compile on 1.12.2 to even check there, I don't have an environment set up to check current code and whether reverting code will make it function as it did before, and many people simply don't use the issues tracker as a discussion board.

**Comment by LabGoblin** [comment]
Popping in to say this is still an issue.
```
Versions
Minecraft v1.16.5
Forge v36.1.16
Akashic Tome v1.4-16
```

**Comment by AndrewSatterfield** [comment]
Still an issue for 1.18. It applies to patchouli as well so even books from different mods can't be added if their manuals are through patchouli.

**Comment by copygirl** [comment]
@Vazkii @Alwinfy @williewillus Apologies for the pings, but is anyone aware of this issue? It's been around a long time, there was a PR for a proposed fix, and many new issues mention this problem.

**Comment by flleeppyy** [comment]
bump

**Comment by williewillus** [comment]
Sorry, there hasn't really been resources to devote to AT as we're all busy with our individual mods and real life. I'll take a look soon (tm).
