### ISSUE TITLE
Trouble adding Open Computers and Immersive Engineering Manuals to tome

### ISSUE THREAD

**Issue by BBoldt** [Vazkii/AkashicTome#6]
Basically, they should both work by default since they have "manual" in the name, but they don't. Also, when I try to add them in with the config, they still don't work.

```
# Configuration file

general {
    B:"Allow all items to be added"=false
    S:"Blacklisted Mods" <
     >
    S:"Mod Aliases" <
        botanicaladdons=botania
        ThermalDynamics=ThermalExpansion
        rftoolsdim=rftools
     >
    S:"Whitelisted Items" <
        evilcraft:originsOfDarkness
        opencomputers:tool:4
        immersiveengineering:tool:3
     >
    S:"Whitelisted Names" <
        book
        tome
        lexicon
        nomicon
        tablet
        manual
        knowledge
        pedia
        compendium
        guide
     >
}
```

Akashic Tome 1.0-3
Open Computers 1.6.0.3rc1
Immersive Engineering 0.10-42

**Comment by Vazkii** [comment]
As it stands, you can't currently use metadata for item defining. I'll work on that soon.

**Comment by BBoldt** [comment]
Is that also the reason they didn't get added with the "manual" name wildcard?

**Comment by Vazkii** [comment]
Yes, because it matches on the item name.

**Comment by BBoldt** [comment]
ah, good to know

**Comment by LemmaEOF** [comment]
@BBoldt, for now the best way to get the manuals in is to turn on "allow all items to be added"

**Comment by BBoldt** [comment]
I whitelisted the word "tool", so a bit less than "all items". Still a lot of things that shouldn't be addable though.
