### ISSUE TITLE
AkashicTome-1.4-16 can crash with older Akashic Tome items present (with older NBT tags).

### ISSUE THREAD

**Issue by Vaelzan** [Vazkii/AkashicTome#62]
The recent update changed the akashictome:displayName tag from string NBT to compound NBT, and there are some situations where there's an unchecked cast to compound NBT, which will cause a crash when the older tags are still present that still have string NBT (eg. a player who had an Akashic Tome prior to the update).

One such problematic line is here: https://github.com/Vazkii/AkashicTome/commit/69f1ff95fb4a9eab395da87ab09c4748cfb4d122#diff-4f5fa3db17ee8ff432cc21935b84a3fcfb3975473fe46fa36ceeacaaa6e04bd3L85

This particular crash should be fixable by just checking if the display name is compound NBT or string NBT before casting. I haven't checked over the rest of the update to see if there are other places where it occurs, since I've been focusing on crash reports from players, such as the one below.

Crash report from one of our players: https://pastebin.com/hp1y1wYS (yes, they have OptiFine installed, which isn't ideal for a report, but the issue will occur regardless).

**Comment by urmet** [comment]
I have one crash report without optifine, if it's better :)
 https://gist.github.com/urmet/a0bf1192b66ed0c34b106f14932141fd

**Comment by Bidgam** [comment]
I'm not sure it's the same, but I get a crash using the tomb when opening Astral Sorcery book in it. Could be all books too, but I stopped at AS when it crashed.

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please open a new issue
