### ISSUE TITLE
book crash while shifting

### ISSUE THREAD

**Issue by DabbingEevee** [Vazkii/AkashicTome#63]
when you press shift on the 1.16 version, the entire game freese as string nbt cant be converted to compound nbt

The game crashed whilst rendering screen
Error: java.lang.ClassCastException: net.minecraft.nbt.StringNBT cannot be cast to net.minecraft.nbt.CompoundNBT
Exit Code: 255

**Comment by DabbingEevee** [comment]
for extra info, i got this crash using the brass modpack

**Comment by mimja23** [comment]
Same issue, any update on fixing?

**Comment by unkidrik** [comment]
Also using brass and getting same crash. seems holding shift while tome is in inventory can cause it and do not need to be using tome.

**Comment by Griefed** [comment]
A user of my modpack just reported a similar issue in https://github.com/Griefed/Survive-Create-Prosper-4/issues/3. The user said:
> Semi-regular crashes when mousing over or transferring items in inventory to a chest. So far the most recent was holding shift over bitumen collected from bitumen ore. Same type error in all cases.

with pastebin https://pastebin.com/6KadwwZW. 

I can replicate it by shift-hovering over the Akashic Tome in the players inventory. See hastebin https://haste.zneix.eu/ipolakiqoj.rb

**Comment by Griefed** [comment]
Further tests with a previous version resulted in no crashes occuring. So, the crash occurs in 
Forge 36.1.16, Minecraft 1.16.5, Akashic Tome version 1.4-16, 
but *not* in 
Forge 36.1.16, Minecraft 1.16.5, Akashic Tome 1.4-15.
Hope that helps!

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please open a new issue
