### ISSUE TITLE
(1.16.5) Doesn't allow duplicates

### ISSUE THREAD

**Issue by delprince979** [Vazkii/AkashicTome#67]
Pretty straight forward; the Akashic Tome won't let you add duplicate items, even though it claims it does. Tried with multiple books, including weird ones like XP Tomes (from XP Tome) and Animal Dictionaries (From Alex's Mobs, added support manually with config). Is this a bug, or is there a config option to allow/disallow duplicates I'm not seeing?

**Comment by iAmAutolocker** [comment]
Having the same issue as well. I edited the configs to make the akashic tome accept all items, but it seems that it won't accept more than one item from a mod (so no putting in two astral tomes).
