### ISSUE TITLE
Missing DisplayName on books before having used them

### ISSUE THREAD

**Issue by NielsPilgaard** [Vazkii/AkashicTome#69]
After adding a book to the Akashic Tome and opening the Tome, I can only see the mod name when I hover over it, not the book name.

Curiously enough, if I NBT-edit `'akashictome:displayName': { text: "Manual Name" }` onto the Tome, the same behaviour persists. No display name on books until they've been  used once.

- AkashicTome-1.4-16

**Screenshots**
![image](https://user-images.githubusercontent.com/12349921/122816064-8b7d2180-d2d6-11eb-87a1-0ba0bd622d8b.png)
![image](https://user-images.githubusercontent.com/12349921/122816111-9a63d400-d2d6-11eb-8fb8-532304ea9943.png)

Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2494 and confirmed locally.

**Comment by Brycey92** [comment]
I'm also having this issue

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please open a new issue
