### ISSUE TITLE
Unable to add Ars Nouveau book natively or via white list

### ISSUE THREAD

**Issue by Seth0067** [Vazkii/AkashicTome#72]
Greetings, on attempting to fix my modpack books integration, I have also discovered that the Ars Nouveau "worn_notebook" is not adding to the Akashic Tome via crafting grid. 

Whitelisting does not allow for the book to be added either.

**Comment by denzuko** [comment]
hey Seth, I'm using the latest version of Ars Nouveau and AkashicTome and haven't had any issues for the warn notebook. Fairly sure your aware that the id for whitelisting is `ars_nouveau:worn_notebook`. So is there any conflicts showing up in the logs?
