### ISSUE TITLE
Log spam when Lexica Botania is in Akashic Tome

### ISSUE THREAD

**Issue by NielsPilgaard** [Vazkii/AkashicTome#73]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3228

When the Lexica Botania is inside an Akashic Tome, the log is filled with `[Render thread/WARN] [botania/]: Failed to render lexicon java.lang.NullPointerException`

[latest2.log](https://github.com/NillerMedDild/Enigmatica6/files/7150240/latest2.log)

### Versions
- Forge-1.16.5-36.2.2
- AkashicTome-1.4-16
- Botania-1.16.5-419

**Comment by flleeppyy** [comment]
Oh...

uh

bump?

**Comment by flleeppyy** [comment]
I've been having this problem for a while now and i just found this issue...
I'd realllyy like to have the Botania lexicon in my akashictome

**Comment by Sandriell** [comment]
This issue still persists on 1.19.2. Spams the log like 50 times a second.

https://gist.github.com/Sandriell/3b0478c7361cddfae94b1618d8a56eeb

**Comment by Uraneptus** [comment]
This issue has been fix from 1.19 onwards, but I'm surprised this has been an isdue for so lobg and no one actually dealt with that lol
