### ISSUE TITLE
Config Issues 1.16.5 version 1.4-16

### ISSUE THREAD

**Issue by MatMaster123** [Vazkii/AkashicTome#77]
Hello! I really love this mod but there are a few frustrating issues. 
The config whitelist doesn't work properly. Only modded items seem to work. Crafting recipes with vanilla items won't appear. 
The same happens when I set "allow all items to be added" to true. None of the vanilla items work.
Also, only one of all books/guides from a mod works. So when a mod adds multiple guides only one can be used in the akashic tome.

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please open a new issue
