### ISSUE TITLE
[1.18.2] Fatal Crash on Instance Load

### ISSUE THREAD

**Issue by HalcyonSeas73** [Vazkii/AkashicTome#86]
Akashic Tome version: 1.5.18
     AutoRegLib version: 1.7.53
Forge version: 40.0.24
Minecraft version: 1.18.2

![Untitled](https://user-images.githubusercontent.com/84727791/159908683-f9e52f54-2754-46ee-9ca7-121e2cf26acc.png)

https://paste.ee/p/uzwhy

**Comment by EccentricVamp** [comment]
The mod hasn't been updated to 1.18.2 yet. It's still on 1.18.1

**Comment by EccentricVamp** [comment]
Cancel that. Looks like Vazkii just put out a version for 1.18.2

**Comment by HalcyonSeas73** [comment]
> Cancel that. Looks like Vazkii just put out a version for 1.18.2

The issue persists with the latest version uploaded minutes ago. (Log: https://paste.ee/p/6RPL0 )
It may be related to some breaking changes JEI made with more recent versions...? Or the tag-related ones with Forge; if the mod hasn't updated to 1.18.2 yet, it shouldn't be listed as compatible on the latest version of the mod on CurseForge...?

**Comment by Corvus20** [comment]
Experiencing this issue as well

**Comment by HalcyonSeas73** [comment]
Crash continues on 1.5.19 (latest as of this posting). I suspect Akashic Tome doesn't yet actually support 1.18.2. Can you confirm, @Vazkii ?

**Comment by Vazkii** [comment]
I could've sworn this was fixed already. I'll have a fix our for it in the next few days, my apologies.

**Comment by HalcyonSeas73** [comment]
> I could've sworn this was fixed already. I'll have a fix our for it in the next few days, my apologies.

Would you like another log posted?

**Comment by HalcyonSeas73** [comment]
> I could've sworn this was fixed already. I'll have a fix our for it in the next few days, my apologies.

👀

**Comment by Jerome226** [comment]
I seems to have the same issue, hoping for a fix soon enough.
