### ISSUE TITLE
[Request] Backport the 1.18 Duplicate Items update to 1.16

### ISSUE THREAD

**Issue by raptor4694** [Vazkii/AkashicTome#91]
I'm currently playing on a custom modpack with Tinker's Construct and noticed the 1.16 version of this mod does not allow me to add all the Tinkers' books into the Tome at once, only 1 at a time. I saw that you just updated the 1.18 version to allow multiple books from the same mod in the tome and was hoping you could backport that update to 1.16.

**Comment by keysmashes** [comment]
would be extremely useful if it could be backported to 1.18.1 as well, though I realise that that's potentially not worth the time

**Comment by EccentricVamp** [comment]
I don't think Vazkii or the other maintainers check back here very often, so you could be waiting a while. My pull request got ignored for about a month, so I just ended up closing it.

If you're interested, I've rewritten this mod. It allows multiple items from the same mod, and it's been backported to 1.16.5 and 1.18.1. https://www.curseforge.com/minecraft/mc-mods/eccentric-tome
