### ISSUE TITLE
Adding too many books causes them to be covered in the menu by the book image

### ISSUE THREAD

**Issue by colossal-wish** [Vazkii/AkashicTome#92]
![image](https://user-images.githubusercontent.com/45466145/167978793-fbc9ce05-95f9-4cb5-a9ce-9b9982ae19db.png)

**Comment by Cerbrus** [comment]
A fix was implemented in this commit: https://github.com/VazkiiMods/AkashicTome/commit/d5d14626a60e5220b6c78eaf18de5a892000a0cf

Disable the book render in your options, and it'll be fine again:

![image](https://github.com/VazkiiMods/AkashicTome/assets/2911988/796ec0ce-7850-4b7b-a22c-cd126b007a96)
