### ISSUE TITLE
Modded enchantment books in tome

### ISSUE THREAD

**Issue by Powerkhan** [Vazkii/AkashicTome#93]
I've been working my own modpack for 1.16.5 and I have 6 added modded enchantment book types. They list in tooltips as minecraft:enchanted_book and under blacklisted mods in the config blacklisting "minecraft" doesn't work. (1 of them is Quark's tome but that blacklists correctly) is there a way to blacklist individual items specifically? Else I'm missing something how these books are being added to my pack and I don't know how to split them from regular minecraft books. (I will show pictures if you need me to.) The mods are listed below of books I'm trying to blacklist from the Akashic tome.

Unique Enchantments
Pisek's Tinker Enchantments
Travel Anchors
Alex's Mobs
Ensorcellation

**Comment by EccentricVamp** [comment]
The Akashic Tome maintainers don't check back here very often, so you might be waiting a while for this issue to be fixed.

If you're interested, I've rewritten this mod and a recently blacklisted `minecraft:enchanted_book`. It's compatible with 1.16.5 and there are couple other custom modpacks already using it.

Check it out at https://github.com/EccentricVamp/EccentricTome and let me know what you think.

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please open a new issue
