### ISSUE TITLE
1.16.5 forge "Allow all items" not allowing all items 

### ISSUE THREAD

**Issue by SparkdotIe** [Vazkii/AkashicTome#95]
In depth duplicate of: https://github.com/VazkiiMods/AkashicTome/issues/77#issue-1070940082

Mc Version: 1.16.5
Modloader Version: Forge - 36.2.34
Mod Version: AkashicTome-1.4-16

Setting "Allow all items" appears to not allow all items to be put into the book, even if the item in question seemingly has no conflict with the function of the book, such as having an alt click function (Music discs for example)

Problem: Only some items are able to be added to the book, Modded music discs for example, but not vanilla.
Extended problem: Discs from the same mod, are not able to be added together when one has already been added

Secondary Problem: Adding the items name to the allowed items list, minecraft:music_disc_13 for example, still does not allow the item to be added, nor does adding the tag "disc" or "music" to the whitelist allow the item to be inserted into the book

The above issues can be replicated with more than discs, such as books with similar names but are separated by nbt tags Cooking for blockheads & Cooking for blockheads [#NoFilter], and items such as ProjectE's Catalytic lens & Philosopher's stone not being allowed after "Allow all items" is enabled.

Screenshots of testing for proof

1a. Modded disc being added successfully (First mod tried) 
![2022-07-06_06 17 07](https://user-images.githubusercontent.com/26665237/177540278-2fd51715-9f79-481b-bfc8-133e7d7f6d21.png)
![2022-07-06_06 16 52](https://user-images.githubusercontent.com/26665237/177540267-7640594c-7953-41d2-8533-10609f920eaa.png)

1b. Modded disc being added successfully (Second mod tried)
![2022-07-06_06 18 08](https://user-images.githubusercontent.com/26665237/177540667-23513e2b-e4dd-496f-ba23-d5e3d44f7461.png)
![2022-07-06_06 17 54](https://user-images.githubusercontent.com/26665237/177540678-81870297-c5bf-45fc-8741-b1701d08fd59.png)

1c. Modded disc being added successfully (Third mod tried)
![2022-07-06_06 18 37](https://user-images.githubusercontent.com/26665237/177540976-2307e87d-f993-44ed-a4d1-a30263420706.png)
![2022-07-06_06 18 32](https://user-images.githubusercontent.com/26665237/177540988-e20af6a0-7b06-4d15-bc53-68a575f9b8df.png)

1d. Modded disc being added successfully (Second disc of the first mod tried)
![2022-07-06_06 18 48](https://user-images.githubusercontent.com/26665237/177541208-d6e2eda6-5486-4156-bc02-740fbdb75275.png)
![2022-07-06_06 18 44](https://user-images.githubusercontent.com/26665237/177541217-0525fd4c-5f4c-42da-aea3-9bbaca2cc433.png)

Examples of the problems:

2a. Vanilla discs not being able to be put into the book
![2022-07-06_06 17 48](https://user-images.githubusercontent.com/26665237/177541390-d3505c16-f16f-4592-a033-b3dc002f84ff.png)
![2022-07-06_06 17 43](https://user-images.githubusercontent.com/26665237/177541402-eba3be73-9bfa-4775-9416-3b5eb6155c2d.png)

2b. Multiple discs from one mod not being able to be put into the book if one already exists
![2022-07-06_06 19 04](https://user-images.githubusercontent.com/26665237/177541691-791b8628-181c-4566-bfdb-765db26e1067.png)
![2022-07-06_06 19 02](https://user-images.githubusercontent.com/26665237/177541715-843b7d06-df98-4533-9a5e-c0a6ca6ca101.png)

Do forgive me if all these images aren't needed for this report.

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please open a new issue
