### ISSUE TITLE
[1.18.2] Akashic Tome breaks item names when you remove a book from it

### ISSUE THREAD

**Issue by vizthex123** [Vazkii/AkashicTome#96]
As you can see here:
![image](https://user-images.githubusercontent.com/31721920/178087896-9cbe7ecd-807c-4969-92a7-ed11013730ce.png)

Game log:
[latest.log](https://github.com/VazkiiMods/AkashicTome/files/9075685/latest.log)

**Comment by krejcar25** [comment]
Same problem with non-botania books:
<img width="271" alt="Screenshot 2022-10-02 at 6 15 04 PM" src="https://user-images.githubusercontent.com/7903442/193464674-e42a5341-e729-4393-bb9d-a01fbdda62f1.png">

Name also gets nested when book is re-inserted into Tome:
<img width="397" alt="Screenshot 2022-10-02 at 6 14 54 PM" src="https://user-images.githubusercontent.com/7903442/193464692-fa8df664-659a-4ec6-9e73-a646a8700c0e.png">

Seen in ATM 7 Skyblock modpack, Akashic Tome version 1.5-20

**Comment by Ingraved** [comment]
Same issue here, in ATM 7 skyblock  (ver. 1.1.3) using Akashic Tome (ver. 1.5-20)

**Comment by Jack-McKalling** [comment]
Also in Seaopolis modpack, version 1.6-23

Affected mod's books:
- AE2
- Deeper and Darker
- Dimensional Dungeons
- Extreme Reactors
- FTB Quests
- Industrial Foregoing
- Mystical Agriculture
- Opolis Utilities
- RFToolsBase
- Sebastrn Lib
- Simple Storage Network
- Thermal Expansion

So all books in this modpack that you start out with. Probably just all books.

**Comment by border999** [comment]
does this mod seem abandoned to anyone else?

**Comment by TristanMisja** [comment]
@border999 Kinda, it's being updated to new versions but bugs aren't being fixed.

Also, the issue effects the 1.19.2 version as well.
