### ISSUE TITLE
[1.18.2] Feature changing books when looking at blocks is using RAW name

### ISSUE THREAD

**Issue by Kanzaji** [Vazkii/AkashicTome#99]
Modpack: [Enigmatica 8](https://github.com/EnigmaticaModpacks/Enigmatica8)
My [Fork](https://github.com/Kanzaji/Enigmatica8/tree/Akashic_Tome_Fix) with Akashic Tome implemented.

Forge: 40.1.73
Mod Version: 1.5.20

Issue:
Feature for changing a book when looking at the block from that mod uses RAW name of the book:
![obraz](https://user-images.githubusercontent.com/60540476/185955759-b9ee9f7e-e7cc-4407-b2ab-5bf28d012dcf.png)

Also please fix the issue of book covering combined manuals if there is too much of them ^^" (#92)

Note: Feature actually works, it is just visual bug.

**Comment by Shibva** [comment]
![image](https://user-images.githubusercontent.com/38770780/197315957-c0ac39d3-24f9-4c37-a951-a7c0060d6359.png)
as a matter of fact tis more than that; books ejected get renamed to this

I can confirm this

**Comment by The-Arcanian** [comment]
Was just coming to report the same thing as Shibva for MC 1.8.2 with Forge 40.2.0 and Akashic Tome 1.5-20.

**Comment by TristanMisja** [comment]
The issue is also on 1.19.2
